[package]
name = "passkeyd-cable"
version = "0.1.0"
edition = "2024"

[dependencies]
webauthn-authenticator-rs = { version = "0.6.1-dev", features = ["cable", "qrcode", "crypto", "ui-cli"] }
tokio = { version = "1.47", features = ["full"] }
anyhow = "1.0.100"
log = "0.4.29"
serde = { workspace = true }
bytes = { workspace = true }
ctap-types = { workspace = true }
